name: fetch_releases

on: workflow_dispatch
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  build:
    name: Run crons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Install Python packages
        run: railway run --service {{secrets.SERVICE_ID}} pip install -r requirements.txt
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: My Command
        run: railway run --service {{SERVICE_ID}} python core.py
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}